server:
  port: 8761
eureka:
  instance:
    #主机名
    hostname: localhost
  client:
    #单节点时没必要注册
    #注册到eureka
    register-with-eureka: false  #服务注册 server不需要注册服务
    #获取注册信息
    fetch-registry: false  #服务发现 调用者使用
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
